name: Write new COS document
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - uses: pnpm/action-setup@v6
        with:
          run_install: true
      - run: pnpm build
      - run: node .
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "write COS document"
